version: '3.8'
    services:
      postgres:
        image: postgres:15
        container_name: macroferro_postgres
        restart: unless-stopped
        environment:
          POSTGRES_USER: ${POSTGRES_USER:-user}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
          POSTGRES_DB: ${POSTGRES_DB:-macroferro_db}
        volumes:
          - postgres_data:/var/lib/postgresql/data
          - ./init_db_scripts:/docker-entrypoint-initdb.d
        ports:
          - "5432:5432"

      pgadmin:
        image: dpage/pgadmin4
        container_name: macroferro_pgadmin
        restart: unless-stopped
        environment:
          PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@example.com}
          PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
        ports:
          - "5050:80"
        depends_on:
          - postgres

      redis:
        image: redis:7-alpine
        container_name: macroferro_redis
        restart: unless-stopped
        ports:
          - "6379:6379"

      qdrant:
        image: qdrant/qdrant:latest
        container_name: macroferro_qdrant
        restart: unless-stopped
        ports:
          - "6333:6333" # gRPC
          - "6334:6334" # REST
        volumes:
          - qdrant_storage:/qdrant/storage

      backend:
        build: ./backend
        container_name: macroferro_backend
        restart: unless-stopped
        ports:
          - "8000:8000"
        volumes:
          - ./backend:/app
        depends_on:
          - postgres
          - redis
          - qdrant
        environment:
          DATABASE_URL: postgresql://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-macroferro_db}
          REDIS_HOST: redis
          REDIS_PORT: 6379
          QDRANT_HOST: qdrant
          QDRANT_PORT_GRPC: 6333
          QDRANT_PORT_REST: 6334
          OPENAI_API_KEY: ${OPENAI_API_KEY} # Debe estar en un .env o ser exportada
        command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

    volumes:
      postgres_data:
      qdrant_storage: